begin;
do $$
declare
 professional uuid := gen_random_uuid(); patient_a uuid := gen_random_uuid(); patient_b uuid := gen_random_uuid();
 a public.appointments; b public.appointments; slot timestamptz := (current_date+7)::timestamp at time zone 'America/Sao_Paulo'; failed boolean;
begin
 insert into auth.users(id,email,raw_user_meta_data) values(professional,professional||'@example.invalid','{"name":"Teste Profissional"}'),(patient_a,patient_a||'@example.invalid','{"name":"Teste Paciente A"}'),(patient_b,patient_b||'@example.invalid','{"name":"Teste Paciente B"}');
 update public.profiles set role='PSYCHOLOGIST' where user_id=professional;
 delete from public.patient_profiles where user_id=professional;
 insert into public.psychologist_profiles(user_id,professional_name,crp,public_slug,verification_status,session_price,deposit_amount) values(professional,'Teste Profissional',professional::text,'test-'||professional,'VERIFIED',150,75);
 insert into public.availability_rules(psychologist_id,weekday,starts_at,ends_at,session_duration_minutes) select professional,i,'08:00','20:00',60 from generate_series(0,6) i;
 slot:=slot+interval '10 hours';
 a:=public.create_appointment_hold_for_patient(patient_a,professional,slot);
 assert a.status='AGUARDANDO_SINAL' and a.expires_at is null and a.session_price=150 and a.deposit_amount=75,'persistent pending reservation';
 failed:=false;
 begin perform public.create_appointment_hold_for_patient(patient_b,professional,slot); exception when others then failed:=sqlerrm='SLOT_CONFLICT'; end;
 assert failed,'duplicate slot rejected';
 failed:=false;
 begin perform public.manage_manual_appointment(patient_b,a.id,'CANCEL'); exception when others then failed:=sqlerrm='NOT_FOUND'; end;
 assert failed,'patient ownership enforced';
 failed:=false;
 begin perform public.manage_manual_appointment(professional,a.id,'CONFIRM'); exception when others then failed:=sqlerrm='DEPOSIT_REQUIRED'; end;
 assert failed,'deposit required before confirmation';
 a:=public.manage_manual_appointment(professional,a.id,'PAYMENT',null,75);
 assert a.status='AGUARDANDO_SINAL' and a.paid_amount=75,'payment does not confirm attendance';
 a:=public.manage_manual_appointment(professional,a.id,'CONFIRM');
 assert a.status='CONFIRMADO','manual confirmation';
 b:=public.create_appointment_hold_for_patient(patient_b,professional,slot+interval '2 hours');
 failed:=false;
 begin perform public.manage_manual_appointment(patient_a,a.id,'RESCHEDULE',b.starts_at); exception when others then failed:=sqlerrm='SLOT_CONFLICT'; end;
 select * into a from public.appointments where id=a.id;
 assert failed and a.starts_at=slot and a.status='CONFIRMADO','failed reschedule preserves original';
 a:=public.manage_manual_appointment(patient_a,a.id,'RESCHEDULE',slot+interval '1 hour');
 assert a.status='AGUARDANDO_SINAL' and a.paid_amount=75 and a.expires_at is null,'reschedule preserves deposit';
 perform public.create_appointment_hold_for_patient(patient_b,professional,slot);
 update public.appointments set starts_at=now()+interval '24 hours',ends_at=now()+interval '25 hours' where id=a.id;
 a:=public.manage_manual_appointment(patient_a,a.id,'CANCEL');
 assert a.refund_status='PENDING' and a.refund_amount=75 and a.status='CANCELADO','exactly 24 hours refundable';
 a:=public.manage_manual_appointment(professional,a.id,'REFUND');
 assert a.refund_status='COMPLETED','manual refund';
 update public.appointments set starts_at=now()+interval '23 hours',ends_at=now()+interval '24 hours' where id=b.id;
 b:=public.manage_manual_appointment(professional,b.id,'PAYMENT',null,150);
 failed:=false;
 begin perform public.manage_manual_appointment(patient_b,b.id,'RESCHEDULE',slot+interval '3 hours'); exception when others then failed:=sqlerrm='TOO_LATE'; end;
 assert failed,'late reschedule rejected';
 b:=public.manage_manual_appointment(patient_b,b.id,'CANCEL');
 assert b.refund_status='NOT_ELIGIBLE' and b.refund_amount=0,'late cancellation no refund';
 assert not has_function_privilege('authenticated','public.manage_manual_appointment(uuid,uuid,text,timestamptz,numeric)','EXECUTE'),'no direct privileged RPC';
 assert not has_column_privilege('authenticated','public.profiles','role','UPDATE'),'no role escalation';
 assert not has_table_privilege('anon','public.schedule_blocks','SELECT'),'private block reasons';
 assert not has_column_privilege('authenticated','public.appointments','status','UPDATE'),'no bypass of booking rules';
end $$;
rollback;
select 'PASS: reservation, overlap, ownership, payment, confirmation, remarcação, 24h, refund and privileges' as result;
