import Link from "next/link";
import Image from "next/image";
import { ArrowRight, CalendarDays, MessageCircle, MoveUpRight, Plus } from "lucide-react";
import { Brand } from "@/components/brand";

export default function Home() {
  return <main className="public-home">
    <header className="public-header"><div className="public-container flex flex-wrap items-center justify-between gap-5 py-5"><Brand /><nav className="hidden items-center gap-8 text-sm font-semibold md:flex" aria-label="Sobre o MindHub"><a href="#seu-espaco" className="nav-link">Seu espaço</a><a href="#como-comecar" className="nav-link">Como começar</a><a href="#duvidas" className="nav-link">Dúvidas</a></nav><Link href="/entrar" className="button-secondary">Entrar <ArrowRight size={16}/></Link></div></header>
    <section className="public-container hero-grid" id="seu-espaco">
      <div className="reveal"><span className="soft-kicker"><span className="size-1.5 rounded-full bg-current"/> Cuidado, no seu tempo</span><h1 className="display-title mt-7">Um tempo<br/>para <em>você.</em></h1><p className="hero-description">Entre tantas coisas para dar conta, você também merece atenção. Este é um espaço para dar o próximo passo, com calma.</p><div className="mt-8 flex flex-wrap items-center gap-5"><Link href="/hub/agendar" className="button-primary !min-h-14 !rounded-full !px-7">Encontrar meu horário <MoveUpRight size={18}/></Link><Link href="/entrar" className="text-link">Já tenho uma conta</Link></div><div className="mt-10 flex items-start gap-3 text-sm leading-6 text-[#64756b]"><CalendarDays size={19} className="mt-0.5 shrink-0"/><p>Escolha um horário que faça sentido para sua rotina.<br className="hidden sm:block"/> O restante, você acompanha por aqui.</p></div></div>
      <figure className="hero-visual reveal"><Image src="/images/acolhimento.png" alt="Uma poltrona junto à luz da janela, em uma composição ilustrativa de acolhimento." width={1122} height={1402} priority sizes="(max-width: 768px) 90vw, 45vw" className="hero-photo"/><figcaption className="hero-note"><span className="hero-note-mark">m</span><div><p className="font-semibold">Não precisa ter todas as respostas.</p><p className="mt-1 text-sm text-[#64756b]">Começar também é uma forma de cuidado.</p></div></figcaption><span className="hero-image-caption">Uma imagem para desacelerar.</span></figure>
    </section>
    <section className="journey-section" id="como-comecar"><div className="public-container"><div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">O primeiro passo</p><h2 className="section-title mt-3">Simples, do começo<br/>ao próximo encontro.</h2></div><p className="max-w-sm leading-7 text-[#64756b]">Sem precisar resolver tudo de uma vez. Você escolhe o horário e acompanha cada etapa no seu espaço.</p></div><div className="grid gap-5 md:grid-cols-3">{[{n:"01",title:"Crie seu espaço",text:"Um cadastro breve para guardar seus horários e facilitar nosso contato.",icon:Plus},{n:"02",title:"Encontre um horário",text:"Consulte os dias disponíveis e escolha o momento que cabe na sua rotina.",icon:CalendarDays},{n:"03",title:"Seguimos em contato",text:"Depois da solicitação e da conferência do sinal, a profissional entra em contato para confirmar.",icon:MessageCircle}].map(({n,title,text,icon:Icon})=><article className="journey-card" key={n}><div className="mb-9 flex items-center justify-between"><span className="text-sm text-[#7b8b80]">{n}</span><Icon size={23} strokeWidth={1.5}/></div><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-[#64756b]">{text}</p></article>)}</div></div></section>
    <section className="public-container grid gap-10 py-20 md:grid-cols-[.85fr_1.15fr]" id="duvidas"><div><p className="eyebrow">Antes de começar</p><h2 className="section-title mt-3">Pode perguntar.</h2><p className="mt-5 max-w-sm leading-7 text-[#64756b]">Algumas respostas para você se sentir à vontade com o próximo passo.</p></div><div>{[{q:"Como meu horário é confirmado?",a:"Ao solicitar, o horário já fica reservado para você. Siga as instruções do sinal no seu agendamento. A profissional confere o recebimento e entra em contato para confirmar o encontro."},{q:"Posso remarcar se surgir um imprevisto?",a:"Sim. Com pelo menos 24 horas de antecedência, você pode escolher outro horário na sua conta. O valor já pago é mantido e o novo horário aguarda confirmação. Mais perto do atendimento, entre em contato com a profissional."},{q:"E se eu precisar cancelar?",a:"Você pode solicitar o cancelamento na sua conta. Com pelo menos 24 horas de antecedência, o valor pago é devolvido pela profissional. Com menos de 24 horas, não há reembolso pela política de agendamento."},{q:"O que encontro no meu espaço?",a:"Seus próximos encontros, o histórico de agendamentos e seus dados de contato. Também é por lá que você acompanha a confirmação, cancela ou remarca um horário."}].map(({q,a})=><details className="faq-item" key={q}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div></section>
    <section className="public-container pb-16"><div className="invitation-banner"><div><p className="text-sm text-white/65">Um passo de cada vez.</p><h2 className="mt-3 font-serif text-3xl sm:text-4xl">Seu próximo encontro começa aqui.</h2></div><Link href="/hub/agendar" className="button-secondary !rounded-full !border-0 !px-7">Escolher um horário <ArrowRight size={18}/></Link></div></section>
    <footer className="public-container flex flex-col justify-between gap-6 border-t border-[#dce3da] py-8 sm:flex-row sm:items-center"><Brand/><p className="text-sm text-[#64756b]">Um espaço para o seu cuidado.</p><Link href="/entrar?next=/app" className="text-link text-sm">Acesso profissional <ArrowRight size={15}/></Link></footer>
  </main>;
}
