import Link from "next/link";
import { ArrowRight, CalendarDays, LockKeyhole, UserRoundCheck } from "lucide-react";
import { Brand } from "@/components/brand";

const schedulePath = "/hub/agendar";

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-[#f6f8f5]">
    <header className="border-b border-[#dce6df] bg-white/90"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-5 sm:px-8"><Brand /><Link href={`/entrar?next=${encodeURIComponent(schedulePath)}`} className="button-secondary px-4 text-sm">Entrar</Link></div></header>
    <section className="relative"><div aria-hidden="true" className="absolute -right-48 top-16 size-[34rem] rounded-full bg-[#d7eee6] blur-3xl" /><div className="relative mx-auto grid max-w-6xl gap-12 px-5 py-16 sm:px-8 sm:py-24 lg:grid-cols-[1.15fr_.85fr] lg:items-center">
      <div><p className="eyebrow">Sua agenda de cuidado</p><h1 className="mt-5 max-w-3xl text-4xl font-black leading-[1.06] tracking-[-.04em] text-[#142139] sm:text-6xl">Seu horário, com clareza e privacidade.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#536579]">Escolha um horário, acompanhe seus atendimentos e mantenha tudo organizado em um só lugar. Com o MindHub, cuidar da sua agenda é simples.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={`/cadastro/paciente?next=${encodeURIComponent(schedulePath)}`} className="button-primary min-h-12 px-6">Agendar atendimento <ArrowRight size={18} /></Link><Link href={`/entrar?next=${encodeURIComponent(schedulePath)}`} className="button-secondary min-h-12 px-6">Já tenho conta</Link></div><p className="mt-5 max-w-xl text-sm leading-6 text-[#68798a]">Acesse sua conta para consultar a disponibilidade e solicitar seu atendimento.</p></div>
      <aside className="card relative p-6 sm:p-8"><p className="eyebrow">Como funciona</p><ol className="mt-6 grid gap-5"><li className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#e4f2ed] text-[#0d6e63]"><UserRoundCheck size={20} /></span><div><h2 className="font-extrabold">Acesse sua conta</h2><p className="muted mt-1 text-sm leading-6">Seu acesso identifica você com segurança.</p></div></li><li className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#e4f2ed] text-[#0d6e63]"><CalendarDays size={20} /></span><div><h2 className="font-extrabold">Escolha um horário liberado</h2><p className="muted mt-1 text-sm leading-6">A disponibilidade é atualizada pela própria profissional.</p></div></li><li className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#e4f2ed] text-[#0d6e63]"><LockKeyhole size={20} /></span><div><h2 className="font-extrabold">Acompanhe em um espaço privado</h2><p className="muted mt-1 text-sm leading-6">Seus dados administrativos ficam restritos à sua conta.</p></div></li></ol></aside>
    </div></section>
    <section className="border-y border-[#dce6df] bg-white"><div className="mx-auto grid max-w-6xl gap-6 px-5 py-12 sm:px-8 md:grid-cols-[.7fr_1.3fr]"><p className="eyebrow">Sobre este espaço</p><div><h2 className="text-2xl font-black tracking-[-.03em] sm:text-3xl">Mais organização para quem atende. Mais facilidade para quem agenda.</h2><p className="muted mt-4 max-w-2xl leading-7">Agenda, pacientes e solicitações reunidos em uma ferramenta prática. A profissional acompanha cada atendimento, enquanto você pode consultar, cancelar ou remarcar pela sua conta.</p></div></div></section>
    <footer className="mx-auto flex max-w-6xl flex-col gap-4 px-5 py-9 text-sm text-[#68798a] sm:flex-row sm:items-center sm:justify-between sm:px-8"><Brand /><p>MindHub · cuidado começa com organização.</p></footer>
  </main>;
}
