"use client";

import { addDays, addMonths, addWeeks, endOfMonth, endOfWeek, format, startOfMonth, startOfWeek } from "date-fns";
import { ptBR } from "date-fns/locale";
import { ChevronLeft, ChevronRight, Plus } from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { StatusBadge } from "@/components/status-badge";

type View = "DIA" | "SEMANA" | "MES";
type Appointment = { id: string; patient_name: string; starts_at: string; status: string };
type Patient = { id: string; name: string };
function intervalFor(view: View, anchor: Date) { if (view === "DIA") return { start: new Date(new Date(anchor).setHours(0, 0, 0, 0)), end: new Date(new Date(anchor).setHours(23, 59, 59, 999)) }; if (view === "MES") return { start: startOfMonth(anchor), end: endOfMonth(anchor) }; return { start: startOfWeek(anchor, { weekStartsOn: 1 }), end: endOfWeek(anchor, { weekStartsOn: 1 }) }; }

export function AgendaWorkspace() {
  const [appointments, setAppointments] = useState<Appointment[]>([]); const [patients, setPatients] = useState<Patient[]>([]); const [view, setView] = useState<View>("SEMANA"); const [anchor, setAnchor] = useState(() => new Date()); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  const interval = useMemo(() => intervalFor(view, anchor), [view, anchor]);
  async function load() { setLoading(true); const response = await fetch(`/api/agenda?from=${encodeURIComponent(interval.start.toISOString())}&to=${encodeURIComponent(interval.end.toISOString())}`, { cache: "no-store" }); const body = await response.json(); if (response.ok) { setAppointments(body.appointments); setPatients(body.patients); } else setMessage(body.error?.message ?? "Não foi possível carregar a agenda."); setLoading(false); }
  useEffect(() => { const current = intervalFor(view, anchor); fetch(`/api/agenda?from=${encodeURIComponent(current.start.toISOString())}&to=${encodeURIComponent(current.end.toISOString())}`, { cache: "no-store" }).then(async (response) => ({ response, body: await response.json() })).then(({ response, body }) => { if (response.ok) { setAppointments(body.appointments); setPatients(body.patients); } else setMessage(body.error?.message ?? "Não foi possível carregar a agenda."); setLoading(false); }); }, [view, anchor]);
  function move(direction: number) { setAnchor((current) => view === "DIA" ? addDays(current, direction) : view === "MES" ? addMonths(current, direction) : addWeeks(current, direction)); }
  async function createAppointment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(""); const form = new FormData(event.currentTarget); const startsAt = `${String(form.get("date"))}T${String(form.get("start"))}:00-03:00`; const response = await fetch("/api/agenda", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ patientId: form.get("patientId"), startsAt }) }); const body = await response.json(); if (!response.ok) return setMessage(body.error?.message ?? "Não foi possível criar o agendamento."); setMessage("Agendamento criado."); setAnchor(new Date(startsAt)); await load(); event.currentTarget.reset(); }
  const title = view === "DIA" ? format(anchor, "EEEE, dd 'de' MMMM", { locale: ptBR }) : `${format(interval.start, "dd MMM", { locale: ptBR })} – ${format(interval.end, "dd MMM yyyy", { locale: ptBR })}`;
  return <div className="grid gap-6 xl:grid-cols-[1fr_330px]"><section className="card overflow-hidden"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-[#e6ecef] p-4"><div className="flex gap-2"><button onClick={() => move(-1)} className="button-secondary !min-h-9 !px-2" aria-label="Período anterior"><ChevronLeft size={18} /></button><button onClick={() => move(1)} className="button-secondary !min-h-9 !px-2" aria-label="Próximo período"><ChevronRight size={18} /></button></div><p className="font-extrabold capitalize">{title}</p><button onClick={() => setAnchor(new Date())} className="button-secondary !min-h-9">Hoje</button></header><div className="flex gap-1 border-b border-[#e6ecef] bg-[#f6f8f9] p-3">{(["DIA", "SEMANA", "MES"] as View[]).map((item) => <button key={item} onClick={() => setView(item)} className={`rounded-lg px-3 py-2 text-sm font-bold ${view === item ? "bg-[#117f72] text-white" : "text-[#516378]"}`}>{item === "MES" ? "Mês" : item[0] + item.slice(1).toLowerCase()}</button>)}</div>{message && <p role="status" className="bg-sky-50 px-4 py-3 text-sm text-sky-900">{message}</p>}<div className="grid gap-3 p-4">{appointments.map((item) => <a href={`/app/agendamentos/${item.id}`} key={item.id} className="flex flex-col gap-3 rounded-xl border border-[#e1e8eb] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-wide text-[#117f72]">{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Sao_Paulo" }).format(new Date(item.starts_at))}</p><h3 className="mt-1 font-extrabold">{item.patient_name}</h3></div><StatusBadge status={item.status} /></a>)}{!loading && !appointments.length && <div className="p-8 text-center text-[#66758d]">Nenhum agendamento neste período.</div>}{loading && <div className="p-8 text-center text-[#66758d]">Carregando…</div>}</div></section><aside className="card h-fit p-5"><h2 className="flex items-center gap-2 font-extrabold"><Plus size={18} /> Novo agendamento</h2><form onSubmit={createAppointment} className="mt-5 grid gap-4"><label className="grid gap-2 text-sm font-bold">Paciente<select required name="patientId" className="field"><option value="">Selecione</option>{patients.map((patient) => <option key={patient.id} value={patient.id}>{patient.name}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Data<input required name="date" type="date" min={format(new Date(), "yyyy-MM-dd")} className="field" /></label><label className="grid gap-2 text-sm font-bold">Horário<input required name="start" type="time" className="field" /></label><button className="button-primary">Criar agendamento</button></form></aside></div>;
}
