"use client";

import { useEffect, useState } from "react";
import { Save } from "lucide-react";
const names = ["Domingo", "Segunda-feira", "Terça-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado"];
type Day = { weekday: number; day: string; enabled: boolean; start: string; end: string };
const blank = names.map((day, weekday) => ({ weekday, day, enabled: false, start: "09:00", end: "17:00" }));
export function AvailabilityEditor() {
  const [days, setDays] = useState<Day[]>(blank); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/availability-rules", { cache: "no-store" }).then(async (r) => ({ ok: r.ok, body: await r.json() })).then(({ ok, body }) => { if (!ok) return setMessage(body.error?.message ?? "Não foi possível carregar."); setDays(blank.map((day) => { const rule = body.rules.find((item: { weekday: number }) => item.weekday === day.weekday); return rule ? { ...day, enabled: true, start: rule.starts_at.slice(0, 5), end: rule.ends_at.slice(0, 5) } : day; })); }); }, []);
  function update(index: number, patch: Partial<Day>) { setDays((current) => current.map((item, i) => i === index ? { ...item, ...patch } : item)); }
  async function save() { setSaving(true); setMessage(""); const response = await fetch("/api/availability-rules", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rules: days.map((item) => ({ weekday: item.weekday, startsAt: item.start, endsAt: item.end, enabled: item.enabled })), sessionDurationMinutes: 60 }) }); const body = await response.json(); setMessage(response.ok ? "Disponibilidade salva." : body.error?.message ?? "Não foi possível salvar."); setSaving(false); }
  return <div className="grid gap-4">{days.map((item, index) => <div key={item.day} className="grid items-center gap-3 rounded-xl border border-[#e3eaed] p-3 lg:grid-cols-[150px_48px_minmax(0,1fr)_20px_minmax(0,1fr)]"><span className="font-bold">{item.day}</span><button type="button" aria-pressed={item.enabled} aria-label={`${item.enabled ? "Desativar" : "Ativar"} ${item.day}`} onClick={() => update(index, { enabled: !item.enabled })} className={`relative h-7 w-12 rounded-full ${item.enabled ? "bg-[#20a596]" : "bg-slate-300"}`}><span className={`absolute top-1 size-5 rounded-full bg-white transition-all ${item.enabled ? "left-6" : "left-1"}`} /></button><input className="field disabled:bg-slate-100" aria-label={`Início de ${item.day}`} type="time" value={item.start} disabled={!item.enabled} onChange={(e) => update(index, { start: e.target.value })} /><span className="text-center text-sm text-slate-400">até</span><input className="field disabled:bg-slate-100" aria-label={`Fim de ${item.day}`} type="time" value={item.end} disabled={!item.enabled} onChange={(e) => update(index, { end: e.target.value })} /></div>)}<button disabled={saving} onClick={save} className="button-primary mt-2"><Save size={18} />{saving ? "Salvando…" : "Salvar alterações"}</button>{message && <p role="status" className="rounded-xl bg-sky-50 p-3 text-sm text-sky-900">{message}</p>}</div>;
}
