"use client";

import Link from "next/link";
import { Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { StatusBadge } from "@/components/status-badge";

type Patient = { patient_id: string; status: "ATIVO" | "INATIVO"; appointments: number; profile?: { name: string; phone: string } };

export function PatientsWorkspace() {
  const [items, setItems] = useState<Patient[]>([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState("TODOS"); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch("/api/patients", { cache: "no-store" }).then(async (response) => ({ response, body: await response.json() })).then(({ response, body }) => { if (response.ok) setItems(body.patients); else setMessage(body.error?.message ?? "Não foi possível carregar os pacientes."); setLoading(false); }); }, []);
  const patients = useMemo(() => items.filter((patient) => { const matches = `${patient.profile?.name ?? ""} ${patient.profile?.phone ?? ""}`.toLowerCase().includes(query.toLowerCase()); return matches && (status === "TODOS" || patient.status === status); }), [items, query, status]);
  async function toggle(patient: Patient) { setMessage(""); const action = patient.status === "ATIVO" ? "deactivate" : "reactivate"; const response = await fetch(`/api/patients/${patient.patient_id}/${action}`, { method: "POST" }); const body = await response.json(); if (!response.ok) return setMessage(body.error?.message ?? "Não foi possível atualizar o paciente."); setItems((current) => current.map((item) => item.patient_id === patient.patient_id ? { ...item, status: body.status } : item)); }
  return <section className="card overflow-hidden"><div className="flex flex-col gap-3 border-b border-[#e5ebee] p-4 sm:flex-row"><label className="relative flex-1"><Search size={18} className="absolute left-3 top-3.5 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="field !pl-10" placeholder="Buscar por nome ou telefone" aria-label="Buscar pacientes" /></label><select value={status} onChange={(event) => setStatus(event.target.value)} className="field sm:w-44" aria-label="Filtrar status"><option value="TODOS">Todos</option><option value="ATIVO">Ativos</option><option value="INATIVO">Inativos</option></select></div>{message && <p role="alert" className="border-b border-[#e9eef0] bg-amber-50 px-4 py-3 text-sm text-amber-900">{message}</p>}<div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-[#f6f8f9] text-xs uppercase tracking-wide text-[#6b7a8e]"><tr><th className="p-4">Paciente</th><th className="p-4">Contato</th><th className="p-4">Consultas</th><th className="p-4">Status</th><th className="p-4 text-right">Ações</th></tr></thead><tbody className="divide-y divide-[#e9eef0]">{patients.map((patient) => <tr key={patient.patient_id}><td className="p-4 font-extrabold">{patient.profile?.name ?? "Paciente"}</td><td className="p-4">{patient.profile?.phone ?? "Não informado"}</td><td className="p-4">{patient.appointments}</td><td className="p-4"><StatusBadge status={patient.status} /></td><td className="p-4 text-right"><div className="flex justify-end gap-3"><button type="button" onClick={() => toggle(patient)} className="font-extrabold text-[#516378]">{patient.status === "ATIVO" ? "Inativar" : "Reativar"}</button><Link href={`/app/pacientes/${patient.patient_id}`} className="font-extrabold text-[#117f72]">Ver perfil</Link></div></td></tr>)}{!loading && !patients.length && <tr><td colSpan={5} className="p-8 text-center text-[#66758d]">Nenhum paciente encontrado.</td></tr>}{loading && <tr><td colSpan={5} className="p-8 text-center text-[#66758d]">Carregando…</td></tr>}</tbody></table></div></section>;
}
