"use client";

import { useEffect, useState, type FormEvent } from "react";
type Me = { email: string; profile: { name: string; phone: string; timezone: string }; roleProfile: { professional_name: string; crp: string; bio: string; public_slug: string; session_duration_minutes: number; deposit_amount: number } };
export function ProfessionalProfileForm() {
  const [me, setMe] = useState<Me | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/me", { cache: "no-store" }).then(async (r) => ({ ok: r.ok, body: await r.json() })).then(({ ok, body }) => ok ? setMe(body) : setMessage(body.error?.message ?? "Não foi possível carregar.")); }, []);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch("/api/me", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), phone: form.get("phone"), professionalName: form.get("professionalName"), bio: form.get("bio"), sessionDurationMinutes: Number(form.get("duration")), depositAmount: Number(form.get("deposit")) }) }); const body = await response.json(); setMessage(response.ok ? "Perfil atualizado." : body.error?.message ?? "Não foi possível salvar."); }
  if (!me) return <div className="card max-w-4xl p-6">{message || "Carregando…"}</div>;
  return <form onSubmit={save} className="card grid max-w-4xl gap-5 p-6"><div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold">Nome de acesso<input className="field" name="name" defaultValue={me.profile.name} required /></label><label className="grid gap-2 text-sm font-bold">Telefone<input className="field" name="phone" defaultValue={me.profile.phone} required /></label><label className="grid gap-2 text-sm font-bold">Nome profissional<input className="field" name="professionalName" defaultValue={me.roleProfile.professional_name} required /></label><label className="grid gap-2 text-sm font-bold">CRP verificado<input className="field bg-slate-50" value={me.roleProfile.crp} readOnly /></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Endereço da agenda<input className="field bg-slate-50" value={`/p/${me.roleProfile.public_slug}`} readOnly /></label><label className="grid gap-2 text-sm font-bold">Duração da sessão<input className="field" name="duration" type="number" min="20" max="240" defaultValue={me.roleProfile.session_duration_minutes} /></label><label className="grid gap-2 text-sm font-bold">Valor do sinal<input className="field" name="deposit" type="number" min="0" step="0.01" defaultValue={me.roleProfile.deposit_amount} /></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Apresentação<textarea className="field min-h-28 py-3" name="bio" defaultValue={me.roleProfile.bio} maxLength={1200} /></label></div>{message && <p role="status" className="rounded-xl bg-sky-50 p-3 text-sm text-sky-900">{message}</p>}<button className="button-primary justify-self-start">Salvar perfil</button></form>;
}

export function PatientProfileForm() {
  const [me, setMe] = useState<Me | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/me", { cache: "no-store" }).then(async (r) => ({ ok: r.ok, body: await r.json() })).then(({ ok, body }) => ok ? setMe(body) : setMessage(body.error?.message ?? "Não foi possível carregar.")); }, []);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch("/api/me", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), phone: form.get("phone") }) }); const body = await response.json(); setMessage(response.ok ? "Perfil atualizado." : body.error?.message ?? "Não foi possível salvar."); }
  if (!me) return <div className="card max-w-2xl p-6">{message || "Carregando…"}</div>;
  return <form onSubmit={save} className="card grid max-w-2xl gap-5 p-6"><label className="grid gap-2 text-sm font-bold">Nome<input className="field" name="name" defaultValue={me.profile.name} required /></label><label className="grid gap-2 text-sm font-bold">E-mail<input className="field bg-slate-50" type="email" value={me.email} readOnly /></label><label className="grid gap-2 text-sm font-bold">Telefone<input className="field" name="phone" defaultValue={me.profile.phone} required /></label>{message && <p role="status" className="rounded-xl bg-sky-50 p-3 text-sm text-sky-900">{message}</p>}<button className="button-primary justify-self-start">Salvar perfil</button></form>;
}
