import { notFound } from "next/navigation";
import { CalendarDays, Clock3, CreditCard, UserRound } from "lucide-react";
import { AppointmentActions } from "@/components/appointment-actions";
import { PageHeading } from "@/components/page-heading";
import { StatusBadge } from "@/components/status-badge";
import { getProfessionalAppointment } from "@/lib/page-data";
import type { AppointmentStatus } from "@/lib/domain/appointments";
function Info({ icon: Icon, label, value }: { icon: typeof CalendarDays; label: string; value: string }) { return <div className="flex gap-3"><Icon className="mt-1 shrink-0 text-[#117f72]" size={20} /><div><p className="muted text-sm">{label}</p><p className="mt-1 font-extrabold">{value}</p></div></div>; }
export default async function AppointmentPage({ params }: PageProps<"/app/agendamentos/[id]">) { const { id } = await params; const item = await getProfessionalAppointment(id); if (!item) notFound(); const starts = new Date(item.starts_at); const duration = Math.round((new Date(item.ends_at).getTime() - starts.getTime()) / 60000); return <><PageHeading title="Detalhes do agendamento" description={`Identificador administrativo ${item.id}`} action={<StatusBadge status={item.status} />} /><section className="card p-6"><h2 className="text-xl font-extrabold">Consulta com {item.patient?.name ?? "Paciente"}</h2><div className="mt-6 grid gap-5 sm:grid-cols-2"><Info icon={CalendarDays} label="Data" value={new Intl.DateTimeFormat("pt-BR", { dateStyle: "long", timeZone: "America/Sao_Paulo" }).format(starts)} /><Info icon={Clock3} label="Horário" value={`${new Intl.DateTimeFormat("pt-BR", { timeStyle: "short", timeZone: "America/Sao_Paulo" }).format(starts)} · ${duration} minutos`} /><Info icon={UserRound} label="Paciente" value={item.patient?.name ?? "Paciente"} /><Info icon={CreditCard} label="Pagamento" value={item.payment?.status ?? "Não registrado"} /></div><div className="mt-7 border-t border-[#e5ebee] pt-6"><h3 className="mb-3 font-extrabold">Atualizar situação</h3><AppointmentActions id={item.id} status={item.status as AppointmentStatus} /></div></section></>; }
