import { BrainCircuit, CheckCircle2, MapPin, Video } from "lucide-react";
import Link from "next/link";
import { Brand } from "@/components/brand";
import { SchedulePicker } from "@/components/schedule-picker";

export default async function PublicSchedulePage({ params }: PageProps<'/p/[slug]'>) {
  const { slug } = await params;
  return <main className="min-h-screen"><header className="border-b border-[#e2e9ec] bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><Brand /><Link href="/entrar" className="text-sm font-extrabold text-[#117f72]">Acessar minha conta</Link></div></header><section className="bg-[linear-gradient(135deg,#0e6e63,#269f91)] text-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-7 px-6 py-10 md:flex-row md:items-center"><div className="flex items-center gap-5"><span className="grid size-20 place-items-center rounded-3xl bg-white/12"><BrainCircuit size={38} /></span><div><p className="text-sm text-white/65">Agenda profissional</p><h1 className="mt-1 text-3xl font-black">Dra. Isadora Bezerra</h1><p className="mt-2 text-sm text-white/75">Psicologia clínica · CRP validado</p></div></div><div className="flex flex-wrap gap-3 text-sm"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-2"><Video size={17} />Online</span><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-2"><MapPin size={17} />São Paulo</span><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-2"><CheckCircle2 size={17} />Perfil verificado</span></div></div></section><section className="mx-auto max-w-7xl px-6 py-10"><div className="mb-8"><p className="eyebrow">Agendamento online</p><h2 className="mt-2 text-3xl font-black tracking-[-.03em]">Escolha um horário disponível</h2><p className="muted mt-2">A reserva fica protegida por 15 minutos enquanto você realiza o pagamento do sinal.</p></div><SchedulePicker psychologistId={slug === 'dra-isadora-bezerra' ? '00000000-0000-0000-0000-000000000001' : slug} depositAmount={50} /></section></main>;
}
